server:
  port: 6000

spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  web:
    resources:
      add-mappings: true