server:
  port: 6002

spring:
  application:
    name: notification
  mail:
    host: smtp.gmail.com
    username: javaholicengineer@gmail.com
    password: ayonvtidnpyvezhz
    port: 587
    protocol: smtp

mail:
  debug: