server:
  port: 6001

spring:
  application:
    name: balance
  datasource:
    url: jdbc:postgresql://localhost:5432/balance
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  web:
    resources:
      add-mappings: true